@startuml Psicologo
left to right direction

actor Psicologo as ps

rectangle "Módulo Psicólogo" {
ps -- (Contratar plan)
ps -- (Gestionar perfil propio)
ps -- (Crear enlace invitado)
ps -- (Ver listado pacientes)
ps -- (Ver registro paciente)
ps -- (Ver estadísticas paciente)
ps -- (Exportar datos paciente)
ps -- (Eliminar registro)
ps -- (Cambiar logo SVG)
}

@enduml
