@startuml Admin
left to right direction

actor Admin as ad

rectangle "Módulo Admin" {
ad -- (Subir logo empresa)
ad -- (Verificar identidad)
ad -- (Bloquear cuenta)
ad -- (Dar de alta psicólogo)
}

@enduml
