@startuml Psicologo
left to right direction

actor Psicologo as ps

rectangle "Módulo Psicólogo" {

ps -- (Contratar o renovar plan)
pa -- (Iniciar sesión)
ps -- (Gestionar perfil profesional)
ps -- (Generar enlace de invitación)

ps -- (Consultar listado de pacientes)
ps -- (Consultar historial del paciente)
ps -- (Consultar estadísticas de paciente)

ps -- (Configurar visibilidad de estadísticas)
ps -- (Exportar datos)

ps -- (Desactivar paciente)
ps -- (Reactivar paciente)

}

(Consultar estadísticas de paciente) ..> (Consultar historial del paciente) : <<include>>

@enduml
