@startuml Paciente
left to right direction

actor Paciente as pa

rectangle "Módulo Paciente" {

pa -- (Registrarse mediante enlace de invitación)
pa -- (Iniciar sesión)
pa -- (Rellenar formulario post-sesión)
pa -- (Solicitar eliminación de cuenta)

pa -- (Ver estadísticas personales)

(Ver estadísticas personales) ..> (Consultar historial de formularios) : <<include>>
pa -- (Consultar historial de formularios)

}

@enduml
