@startuml Paciente
left to right direction

actor Paciente as pa

rectangle "Módulo Paciente" {
pa -- (Iniciar sesión)
pa -- (Introducir datos)
pa -- (Ver estadísticas)
pa -- (Registrarse por enlace)
pa -- (Acceder al panel)
pa -- (Exportar datos*?)
pa -- (Guardar registro)
pa -- (Eliminar cuenta - cuenta desactivada)
}

@enduml
